import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docSidebar: [{ type: "autogenerated", dirName: "." }],
  // But you can create a sidebar manually
  // docSidebar: [
  //   {
  //     type: "category",
  //     label: "Tutorial",
  //     items: ["tutorial-basics/create-a-document"],
  //   },
  // ],
};

export default sidebars;
